config/routes.rb
Rails.application.routes.draw do
  root to: "repos#index"

  scope '/*repo_id', repo_id: /[^\/]+\/[^\/]+/ do
    get '/' => 'reports#index', as: :repo
    get '/:date' => 'reports#show', as: :repo_date, date: /\d\d\d\d-\d\d-\d\d/
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  serialize :data, JSON

  scope :repo, -> (name) { where(repo: name) }
  scope :on_date, -> (date) {
    where("created_at >= ? AND created_at <= ?",
      Date.parse(date).beginning_of_day,
      Date.parse(date).end_of_day)
  }

  def json=(string)
    self.data = JSON.parse(string)
  end

  def json
    JSON.dump(data)
  end

  def to_param
    created_at.to_date.iso8601
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @repo = params[:repo_id]
    @reports = Report.where(repo: @repo).order("created_at ASC")
  end

  def show
    @repo = params[:repo_id]
    @date = params[:date]
    @report = Report.repo(@repo).on_date(@date).first
    @html = HowIs.from_hash(@report.data).to_html
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @repos = Repo.names
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/reports/index.html.erb
<h1>how is <%= @repo %>?</h1>

<ul>
  <%- @reports.each do |report| -%>
  <li><%= link_to report.created_at.to_date.iso8601, repo_date_path(@repo, report) %></li>
  <%- end -%>
</ul>

app/views/reports/show.html.erb
<h1>how was <%= @repo %> on <%= @date %>?</h1>

<p><%= raw(@html) %></p>

app/views/repos/index.html.erb
<h1>how are those repos, anyway?</h1>

<ul>
  <%- @repos.each do |repo| -%>
  <li><%= link_to repo, repo_path(repo) %></li>
  <%- end -%>
</ul>